// ========================================
// Clean Energy Atlas — News Feed
// Curated energy news (2024-2025)
// ========================================

var energyNewsItems = [

  // ===== WIND =====
  { title: "US Offshore Wind Surpasses 5 GW Installed Capacity Milestone", summary: "The United States reached a significant offshore wind milestone as the 5 GW mark was crossed, with major projects off Massachusetts, New York, and New Jersey entering service.", country: "USA", date: "2025-03-10", category: "Market", url: "https://www.google.com/search?q=US+Offshore+Wind+Surpasses+5+GW+Installed+Capacity+Milestone+USA" },
  { title: "UK Awards Record 9.6 GW in Sixth Contracts for Difference Round", summary: "The UK government's sixth CfD auction round awarded contracts to 9.6 GW of offshore and onshore wind projects at historically competitive strike prices.", country: "UK", date: "2025-03-28", category: "Policy", url: "https://www.google.com/search?q=UK+Awards+Record+9.6+GW+in+Sixth+Contracts+for+Difference+Round+UK" },
  { title: "China Installs 100 GW of New Wind Capacity in Single Year for First Time", summary: "China's National Energy Administration confirmed 100 GW of new wind installations in 2024, a world record for any country.", country: "China", date: "2025-02-28", category: "Market", url: "https://www.google.com/search?q=China+Installs+100+GW+of+New+Wind+Capacity+in+Single+Year+for+First+Time+China" },
  { title: "Germany Hits 30 GW Offshore Wind Capacity Two Years Ahead of Schedule", summary: "Germany surpassed 30 GW of offshore wind capacity in the North Sea, reaching the national target set for 2030 early.", country: "Germany", date: "2025-03-05", category: "Market", url: "https://www.google.com/search?q=Germany+Hits+30+GW+Offshore+Wind+Capacity+Two+Years+Ahead+of+Schedule+Germany" },
  { title: "India Achieves 50 GW Onshore Wind Milestone", summary: "India crossed the 50 GW installed onshore wind capacity milestone, with Rajasthan and Gujarat leading growth.", country: "India", date: "2025-02-10", category: "Market", url: "https://www.google.com/search?q=India+Achieves+50+GW+Onshore+Wind+Milestone+India" },
  { title: "Hornsea Three Offshore Wind Farm Begins Commercial Operations", summary: "Orsted's 2,800 MW Hornsea Three project off the Yorkshire coast entered commercial operation.", country: "UK", date: "2025-02-14", category: "Project", url: "https://www.google.com/search?q=Hornsea+Three+Offshore+Wind+Farm+Begins+Commercial+Operations+UK" },
  { title: "Denmark Plans 10 GW Energy Island in the North Sea", summary: "Denmark advanced plans for the world's first artificial energy island, designed to collect and distribute 10 GW of offshore wind power.", country: "Denmark", date: "2025-01-20", category: "Project", url: "https://www.google.com/search?q=Denmark+Plans+10+GW+Energy+Island+in+the+North+Sea+Denmark" },
  { title: "Vineyard Wind Turbine Installation Resumes After Safety Review", summary: "Vineyard Wind's 800 MW offshore project off Massachusetts resumed turbine installation following a federal safety investigation.", country: "USA", date: "2025-01-22", category: "Project", url: "https://www.google.com/search?q=Vineyard+Wind+Turbine+Installation+Resumes+After+Safety+Review+USA" },
  { title: "Ming Yang Smart Energy Launches 22 MW Offshore Turbine", summary: "Chinese manufacturer Ming Yang unveiled a 22 MW offshore wind turbine with a 310-meter rotor diameter, the largest ever.", country: "China", date: "2024-10-08", category: "Technology", url: "https://www.google.com/search?q=Ming+Yang+Smart+Energy+Launches+22+MW+Offshore+Turbine+China" },
  { title: "Inflation Reduction Act Tax Credits Drive Record US Wind Installations", summary: "IRA production tax credits drove US onshore wind to a record 19 GW of new installations in 2024.", country: "USA", date: "2025-01-08", category: "Policy", url: "https://www.google.com/search?q=Inflation+Reduction+Act+Tax+Credits+Drive+Record+US+Wind+Installations+USA" },

  // ===== SOLAR =====
  { title: "Global Solar Installations Reach 350 GW in 2024, Shattering Records", summary: "Worldwide solar PV installations hit 350 GW in 2024, led by China, the US, and India, marking the highest ever annual total.", country: "Global", date: "2025-02-15", category: "Market", url: "https://www.google.com/search?q=Global+Solar+Installations+Reach+350+GW+in+2024%2C+Shattering+Records+Global" },
  { title: "India Commissions World's Largest Single-Site Solar Park at 4.75 GW", summary: "India's Bhadla Solar Park in Rajasthan reached full capacity at 4.75 GW, making it the largest solar installation on Earth.", country: "India", date: "2025-03-01", category: "Project", url: "https://www.google.com/search?q=India+Commissions+World%27s+Largest+Single-Site+Solar+Park+at+4.75+GW+India" },
  { title: "US Solar Manufacturing Doubles Under IRA Incentives", summary: "US domestic solar panel manufacturing capacity doubled to 30 GW annually as IRA tax credits attracted $12 billion in factory investments.", country: "USA", date: "2025-01-18", category: "Investment", url: "https://www.google.com/search?q=US+Solar+Manufacturing+Doubles+Under+IRA+Incentives+USA" },
  { title: "Saudi Arabia Awards 5 GW Solar Mega-Contract to ACWA Power", summary: "Saudi Arabia's Renewable Energy Development Office awarded ACWA Power a 5 GW solar contract as part of Vision 2030 targets.", country: "Saudi Arabia", date: "2024-12-05", category: "Investment", url: "https://www.google.com/search?q=Saudi+Arabia+Awards+5+GW+Solar+Mega-Contract+to+ACWA+Power+Saudi+Arabia" },
  { title: "Perovskite-Silicon Tandem Solar Cells Break 33.9% Efficiency Record", summary: "LONGi Green Energy achieved 33.9% efficiency with tandem perovskite-silicon cells, approaching theoretical limits.", country: "China", date: "2025-02-22", category: "Technology", url: "https://www.google.com/search?q=Perovskite-Silicon+Tandem+Solar+Cells+Break+33.9%25+Efficiency+Record+China" },
  { title: "Australia Plans 20 GW Sun Cable Solar-Battery Export to Singapore", summary: "The massive Sun Cable project in Northern Territory moved to construction phase, planning 20 GW of solar with undersea cable export.", country: "Australia", date: "2024-11-10", category: "Project", url: "https://www.google.com/search?q=Australia+Plans+20+GW+Sun+Cable+Solar-Battery+Export+to+Singapore+Australia" },
  { title: "European Solar Capacity Passes 300 GW Total Installed", summary: "Europe crossed the 300 GW solar milestone as Germany, Spain, and Italy led installations across the continent.", country: "Europe", date: "2025-03-12", category: "Market", url: "https://www.google.com/search?q=European+Solar+Capacity+Passes+300+GW+Total+Installed+Europe" },
  { title: "Brazil Becomes World's 5th Largest Solar Market", summary: "Brazil added 18 GW of solar in 2024, driven by distributed generation and utility-scale projects in the northeast.", country: "Brazil", date: "2025-01-30", category: "Market", url: "https://www.google.com/search?q=Brazil+Becomes+World%27s+5th+Largest+Solar+Market+Brazil" },
  { title: "Bifacial Solar Panels Now Represent 80% of Global Shipments", summary: "Bifacial panel technology reached 80% market share in 2024, up from 10% five years ago, boosting energy yields 10-20%.", country: "Global", date: "2024-10-15", category: "Technology", url: "https://www.google.com/search?q=Bifacial+Solar+Panels+Now+Represent+80%25+of+Global+Shipments+Global" },
  { title: "Japan Approves 2 GW Floating Solar Project in Kagoshima Bay", summary: "Japan green-lit the world's largest floating solar installation, a 2 GW array in Kagoshima Bay using next-gen anchoring systems.", country: "Japan", date: "2024-09-20", category: "Project", url: "https://www.google.com/search?q=Japan+Approves+2+GW+Floating+Solar+Project+in+Kagoshima+Bay+Japan" },

  // ===== HYDRO =====
  { title: "China's Baihetan Dam Reaches Full 16 GW Operational Capacity", summary: "Baihetan, the world's second-largest hydropower station, reached full 16 GW capacity with all 16 turbines operational.", country: "China", date: "2025-01-05", category: "Project", url: "https://www.google.com/search?q=China%27s+Baihetan+Dam+Reaches+Full+16+GW+Operational+Capacity+China" },
  { title: "Ethiopia Begins Filling Grand Ethiopian Renaissance Dam's Final Stage", summary: "Ethiopia commenced the fifth and final filling stage of the 6.45 GW GERD, Africa's largest hydroelectric dam.", country: "Ethiopia", date: "2025-03-15", category: "Project", url: "https://www.google.com/search?q=Ethiopia+Begins+Filling+Grand+Ethiopian+Renaissance+Dam%27s+Final+Stage+Ethiopia" },
  { title: "Norway Pumped Hydro Storage Investments Surge 40%", summary: "Norway increased investment in pumped hydro storage by 40% year-over-year, positioning as Europe's green battery.", country: "Norway", date: "2024-11-22", category: "Investment", url: "https://www.google.com/search?q=Norway+Pumped+Hydro+Storage+Investments+Surge+40%25+Norway" },
  { title: "Brazil's Belo Monte Dam Generates Record Annual Output", summary: "Belo Monte, an 11.2 GW facility on the Xingu River, set an annual generation record of 40.1 TWh in 2024.", country: "Brazil", date: "2025-02-08", category: "Project", url: "https://www.google.com/search?q=Brazil%27s+Belo+Monte+Dam+Generates+Record+Annual+Output+Brazil" },
  { title: "India Plans 30 GW of New Pumped Storage Hydro by 2032", summary: "India announced plans for 30 GW of pumped storage hydropower projects to support grid integration of variable renewables.", country: "India", date: "2024-12-18", category: "Policy", url: "https://www.google.com/search?q=India+Plans+30+GW+of+New+Pumped+Storage+Hydro+by+2032+India" },

  // ===== GEOTHERMAL =====
  { title: "Kenya Becomes World's 7th Largest Geothermal Producer at 1 GW", summary: "Kenya reached 1 GW of geothermal capacity with the Olkaria V expansion, generating 47% of the nation's electricity.", country: "Kenya", date: "2025-02-20", category: "Market", url: "https://www.google.com/search?q=Kenya+Becomes+World%27s+7th+Largest+Geothermal+Producer+at+1+GW+Kenya" },
  { title: "Fervo Energy's Enhanced Geothermal System Achieves Commercial Scale in Utah", summary: "Fervo Energy's Project Red in Utah began commercial operations, proving enhanced geothermal systems can scale.", country: "USA", date: "2025-01-15", category: "Technology", url: "https://www.google.com/search?q=Fervo+Energy%27s+Enhanced+Geothermal+System+Achieves+Commercial+Scale+in+Utah+USA" },
  { title: "Iceland's Theistareykir Geothermal Plant Expansion Adds 100 MW", summary: "Iceland expanded the Theistareykir plant by 100 MW, bringing total capacity to 190 MW serving aluminum smelters.", country: "Iceland", date: "2024-10-28", category: "Project", url: "https://www.google.com/search?q=Iceland%27s+Theistareykir+Geothermal+Plant+Expansion+Adds+100+MW+Iceland" },
  { title: "Indonesia Targets 8 GW Geothermal by 2030 Under New Policy", summary: "Indonesia issued new geothermal exploration incentives targeting 8 GW total capacity, up from 2.4 GW today.", country: "Indonesia", date: "2024-09-14", category: "Policy", url: "https://www.google.com/search?q=Indonesia+Targets+8+GW+Geothermal+by+2030+Under+New+Policy+Indonesia" },
  { title: "Google Partners with Fervo for 115 MW Geothermal to Power Data Centers", summary: "Google signed a corporate PPA with Fervo Energy for 115 MW of next-gen geothermal power dedicated to data center operations.", country: "USA", date: "2024-08-12", category: "Investment", url: "https://www.google.com/search?q=Google+Partners+with+Fervo+for+115+MW+Geothermal+to+Power+Data+Centers+USA" },

  // ===== NUCLEAR =====
  { title: "Vogtle Unit 4 Begins Commercial Operation, Completing US First New Nuclear in Decades", summary: "Georgia Power's Vogtle Unit 4 entered commercial service, completing the first new US nuclear construction in over 30 years.", country: "USA", date: "2025-03-20", category: "Project", url: "https://www.google.com/search?q=Vogtle+Unit+4+Begins+Commercial+Operation%2C+Completing+US+First+New+Nuclear+in+Decades+USA" },
  { title: "France Announces 6 New EPR2 Reactor Sites for 10 GW Expansion", summary: "President Macron confirmed six new EPR2 reactor sites, targeting 10 GW of new nuclear capacity by 2040.", country: "France", date: "2025-02-25", category: "Policy", url: "https://www.google.com/search?q=France+Announces+6+New+EPR2+Reactor+Sites+for+10+GW+Expansion+France" },
  { title: "South Korea Wins $22 Billion Contract for Czech Nuclear Plant", summary: "KHNP won the contract to build two APR1400 reactors at Dukovany, the largest South Korean nuclear export deal.", country: "South Korea", date: "2024-12-10", category: "Investment", url: "https://www.google.com/search?q=South+Korea+Wins+%2422+Billion+Contract+for+Czech+Nuclear+Plant+South+Korea" },
  { title: "China Connects Four New Nuclear Reactors to Grid in Single Year", summary: "China connected four new nuclear units in 2024, adding 4.5 GW and bringing total operating capacity to 60 GW.", country: "China", date: "2025-01-28", category: "Market", url: "https://www.google.com/search?q=China+Connects+Four+New+Nuclear+Reactors+to+Grid+in+Single+Year+China" },
  { title: "NuScale Small Modular Reactor Receives Full NRC Design Certification", summary: "NuScale Power's 77 MW small modular reactor became the first SMR to receive full NRC design certification.", country: "USA", date: "2025-01-10", category: "Technology", url: "https://www.google.com/search?q=NuScale+Small+Modular+Reactor+Receives+Full+NRC+Design+Certification+USA" },
  { title: "Microsoft Signs Nuclear PPA to Power AI Data Centers", summary: "Microsoft signed a 20-year PPA for 835 MW from Constellation Energy's Crane Clean Energy Center (formerly Three Mile Island).", country: "USA", date: "2024-09-25", category: "Investment", url: "https://www.google.com/search?q=Microsoft+Signs+Nuclear+PPA+to+Power+AI+Data+Centers+USA" },

  // ===== HYDROGEN =====
  { title: "NEOM Green Hydrogen Project Reaches 50% Construction Completion", summary: "The $8.5 billion NEOM Helios green hydrogen project in Saudi Arabia reached 50% completion, on track for 2026 output.", country: "Saudi Arabia", date: "2025-03-08", category: "Project", url: "https://www.google.com/search?q=NEOM+Green+Hydrogen+Project+Reaches+50%25+Construction+Completion+Saudi+Arabia" },
  { title: "EU Approves €4.6 Billion in Hydrogen Infrastructure Subsidies", summary: "The European Commission approved €4.6 billion in state aid for hydrogen production, storage, and pipeline infrastructure.", country: "Europe", date: "2025-02-12", category: "Policy", url: "https://www.google.com/search?q=EU+Approves+%E2%82%AC4.6+Billion+in+Hydrogen+Infrastructure+Subsidies+Europe" },
  { title: "Japan Receives First Commercial Green Hydrogen Shipment from Australia", summary: "Japan's JERA received the first commercial-scale green hydrogen cargo from Australia's Pilbara region via liquid carrier.", country: "Japan", date: "2025-01-25", category: "Market", url: "https://www.google.com/search?q=Japan+Receives+First+Commercial+Green+Hydrogen+Shipment+from+Australia+Japan" },
  { title: "US DOE Announces $7 Billion for Seven Regional Hydrogen Hubs", summary: "The Department of Energy finalized $7 billion in funding for seven regional clean hydrogen hubs across the United States.", country: "USA", date: "2024-11-15", category: "Policy", url: "https://www.google.com/search?q=US+DOE+Announces+%247+Billion+for+Seven+Regional+Hydrogen+Hubs+USA" },
  { title: "Green Hydrogen Production Cost Falls Below $3/kg in Optimal Locations", summary: "BloombergNEF reports green hydrogen production costs have fallen below $3/kg in the best solar and wind resource areas.", country: "Global", date: "2024-10-20", category: "Market", url: "https://www.google.com/search?q=Green+Hydrogen+Production+Cost+Falls+Below+%243%2Fkg+in+Optimal+Locations+Global" },

  // ===== STORAGE =====
  { title: "Global Battery Storage Installations Double to 120 GWh in 2024", summary: "Annual battery energy storage deployments doubled to 120 GWh globally, driven by China, the US, and Europe.", country: "Global", date: "2025-03-05", category: "Market", url: "https://www.google.com/search?q=Global+Battery+Storage+Installations+Double+to+120+GWh+in+2024+Global" },
  { title: "California's Moss Landing Expands to 1.6 GW, World's Largest Battery", summary: "Vistra Energy completed the Moss Landing expansion to 1.6 GW / 6.4 GWh, making it the world's largest battery storage facility.", country: "USA", date: "2025-02-18", category: "Project", url: "https://www.google.com/search?q=California%27s+Moss+Landing+Expands+to+1.6+GW%2C+World%27s+Largest+Battery+USA" },
  { title: "CATL Launches 5 MWh Containerized Battery for Grid Storage", summary: "CATL unveiled its Tener system, a 5 MWh containerized battery with zero degradation guarantee for five years.", country: "China", date: "2025-01-12", category: "Technology", url: "https://www.google.com/search?q=CATL+Launches+5+MWh+Containerized+Battery+for+Grid+Storage+China" },
  { title: "Australia Approves 1.2 GW Waratah Super Battery Near Sydney", summary: "Australia approved the 1.2 GW / 4.8 GWh Waratah Super Battery, the Southern Hemisphere's largest storage project.", country: "Australia", date: "2024-11-30", category: "Project", url: "https://www.google.com/search?q=Australia+Approves+1.2+GW+Waratah+Super+Battery+Near+Sydney+Australia" },
  { title: "Iron-Air Battery Startup Form Energy Begins Grid Deployment", summary: "Form Energy started deploying its 100-hour iron-air batteries in Georgia, offering multi-day storage at $20/kWh.", country: "USA", date: "2024-10-05", category: "Technology", url: "https://www.google.com/search?q=Iron-Air+Battery+Startup+Form+Energy+Begins+Grid+Deployment+USA" },
  { title: "UK Grid Battery Revenue Hits £1.2 Billion in 2024", summary: "UK battery storage operators earned £1.2 billion from grid services in 2024, driving a wave of new project financings.", country: "UK", date: "2025-02-28", category: "Investment", url: "https://www.google.com/search?q=UK+Grid+Battery+Revenue+Hits+%C2%A31.2+Billion+in+2024+UK" },

  // ===== DATA CENTERS =====
  { title: "Global Data Center Power Demand Projected to Reach 100 GW by 2030", summary: "IEA projects global data center electricity consumption will double to 100 GW by 2030, driven by AI and cloud computing.", country: "Global", date: "2025-03-18", category: "Market", url: "https://www.google.com/search?q=Global+Data+Center+Power+Demand+Projected+to+Reach+100+GW+by+2030+Global" },
  { title: "Microsoft Commits to 100% Carbon-Free Energy for All Data Centers by 2028", summary: "Microsoft accelerated its clean energy commitment, pledging 100% carbon-free electricity for all global data centers by 2028.", country: "USA", date: "2025-02-05", category: "Policy", url: "https://www.google.com/search?q=Microsoft+Commits+to+100%25+Carbon-Free+Energy+for+All+Data+Centers+by+2028+USA" },
  { title: "Google Signs Record 1.4 GW Renewable PPA Portfolio for Data Centers", summary: "Google signed a record 1.4 GW portfolio of wind, solar, and geothermal PPAs to power data centers across three continents.", country: "Global", date: "2025-01-20", category: "Investment", url: "https://www.google.com/search?q=Google+Signs+Record+1.4+GW+Renewable+PPA+Portfolio+for+Data+Centers+Global" },
  { title: "Amazon Web Services Opens First Nuclear-Powered Data Center Campus", summary: "AWS opened a data center campus in Virginia directly powered by an adjacent nuclear plant through a dedicated PPA.", country: "USA", date: "2024-12-08", category: "Project", url: "https://www.google.com/search?q=Amazon+Web+Services+Opens+First+Nuclear-Powered+Data+Center+Campus+USA" },
  { title: "Singapore Lifts Data Center Moratorium with Green Energy Requirement", summary: "Singapore lifted its data center construction moratorium, requiring all new facilities to use 100% renewable energy.", country: "Singapore", date: "2024-11-05", category: "Policy", url: "https://www.google.com/search?q=Singapore+Lifts+Data+Center+Moratorium+with+Green+Energy+Requirement+Singapore" },
  { title: "Meta Announces 2 GW Solar Farm to Power Iowa Data Center Complex", summary: "Meta committed to building a 2 GW solar farm in Iowa dedicated to powering its growing AI training data center cluster.", country: "USA", date: "2024-09-30", category: "Investment", url: "https://www.google.com/search?q=Meta+Announces+2+GW+Solar+Farm+to+Power+Iowa+Data+Center+Complex+USA" }
];
